Typeform/embed

.github/PULL_REQUEST_TEMPLATE.md
[Reference Ticket ](https://jira.typeform.tf/browse/DIST-145)
- Updates the pull request template
=> chore(DIST-145): Update pull request template

.travis.yml
Should fix the issue: https://travis-ci.com/github/Typeform/embed/jobs/333835315
=> chore: Added npm token installation

.travis.yml, demo/behavioral/exit.html, demo/behavioral/load.html, demo/behavioral/scroll.html, demo/behavioral/time.html, demo/index.html, src/core/attributes.js, src/core/attributes.spec.js, src/core/make-popup.js, src/core/make-popup.spec.js, src/core/utils/popup-auto-open.js, src/core/utils/popup-auto-open.spec.js
Popup can be opened on:
- load (same as current 'auto-open' feature)
- exit (allows modifying the sensitivity of threshold at the top of the page in pixels)
- time (in milliseconds)
- scroll (in percentage)
Demo available: http://tf.w2.sk/demo/
=> feat(DIST-193): Open popup using behavioral trigger

README.md, demo/index.html, demo/popup-api-autoopen.html, demo/popup-api.html, demo/popup.html, e2e/spec/functional/popup.spec.js, e2e/spec/visual/popup.spec.js, src/core/make-popup.js, src/core/views/popup.js, src/core/views/popup.spec.js, src/embed.js
For popup mode "side_panel" you can also set width and height of the popup. It needs to specify "container" in order for slide animation to work correctly.
https://jira.typeform.tf/browse/DIST-306
=> fix(DIST-306): Add side panel popup type

.travis.yml, demo/behavioral-api/exit-api.html, demo/behavioral-api/load-api.html, demo/behavioral-api/scroll-api.html, demo/behavioral-api/time-api.html, demo/behavioral-code/exit-code.html, demo/behavioral-code/load-code.html, demo/behavioral-code/scroll-code.html, demo/behavioral-code/time-code.html, demo/index.html, demo/popup-api.html, demo/popup.html, e2e/cypress-utils.js, e2e/spec/functional/behavioral-popup.spec.js, e2e/spec/functional/popup.spec.js, e2e/spec/visual/popup.spec.js
Test embeds created via embed code and API
=> feat(DIST-301): Add functional tests for behavioral triggers from DIST-193

src/core/views/popup.js
=> fix(DIST-382): Add shadow transition to sidetab

webpack.config.js
=> feat(DIST-390): Added node.js support

README.md
This took me a second to work through how it works with React hooks, might save someone some time in the future.
=> React Hooks Example

webpack.config.js
Removes source maps from production bundle.
[Ticket DIST-432](https://jira.typeform.tf/browse/DIST-432)
=> chore(DIST-432): Remove source maps from deployment

src/core/views/components/spinner.js
=> fix(DIST-454): Fixes spinner animation

README.md
=> fix(DIST-476): Fix README

package.json, yarn.lock
react and react-dom shouldn't be pinned so i dont need to install multiple versions of react to use this package
tests ran, just make sure it's still loading as you expect.
this doesn't close that issue, it's just a small part of it.
=> perf: Move react, react-dom to peer deps

.travis.yml
=> fix(DIST-426): Use latest Jarvis version

src/core/utils/embed-permissions.js
=> feat: Allow fullscreen for embedded videos

src/core/views/popup.js
Adds a minimum size for Embed popups.
[Reference Ticket DIST-549](https://jira.typeform.tf/browse/DIST-549)
I went for the easiest path, and just adding the values inside the desktop popup component
=> chore(DIST-549): Add minumum size for popups on desktop

demo/popup-api.html, demo/popup.html
=> fix(DIST-548): Make side tab button reponsive to text

e2e/spec/functional/popup.spec.js, src/core/make-fullscreen.js, src/core/make-popup.js, src/core/utils/index.js, src/core/views/mobile-modal.js
https://jira.typeform.tf/browse/DIST-568
https://twitter.com/mostly_gripes/status/1332380963406483458
=> fix(DIST-568): Restore viewport when popup is closed

.github/workflows/release.yml
Release workflow needs to checkout the repo first :)
=> chore(DIST-589): Update release Github Action workflow

README.md
=> chore: Update README badges

README.md, package.json, packages/embed-react/package.json, packages/embed/jest.config.json, packages/embed/package.json, packages/embed/src/base/actionable-options.ts, packages/embed/src/factories/create-popup/create-popup.spec.ts, packages/embed/src/factories/create-popup/create-popup.ts, packages/embed/src/factories/create-widget/create-widget.spec.ts, packages/embed/src/factories/create-widget/create-widget.ts, packages/embed/src/utils/build-iframe.src.spec.ts, packages/embed/src/utils/create-iframe.spec.ts, packages/embed/tsconfig.json, yarn.lock
Add unit tests for existing code.
Merge #136 first
=> test(DIST-711): Add jest support

README.md, package.json, packages/embed-kitchen-sink/.eslintrc.js, packages/embed-kitchen-sink/.storybook/main.js, packages/embed-kitchen-sink/.storybook/preview.js, packages/embed-kitchen-sink/README.md, packages/embed-kitchen-sink/package.json, packages/embed-kitchen-sink/stories/Popup.stories.js, packages/embed-kitchen-sink/stories/Widget.stories.js, packages/embed/README.md, packages/embed/package.json, yarn.lock
Storybook runs demo of the embed library.
=> feat(DIST-691): Add storybook

package.json, packages/embed/package.json, yarn.lock
Starts demo server and runs functional tests with single command. This will help with running functional tests in Github Actions.
=> feat(DIST-691): Add functional tests script for CI

.github/workflows/pull-request-next.yml
`next` branch is now protected, requires PRs, reviews and passed CI checks (build, lint, unit test, functional test).
=> feat(DIST-717): Setup Github Actions for @next version

packages/embed/package.json, packages/embed/webpack.config.js, yarn.lock
Add webpack, webpack-cli and ts-loadr as devDependencies for embed
Add webpack config for browser bundle
Add script to package.json to build with webpack
=> chore: add webpack for embed browser build

packages/embed/package.json, packages/embed/webpack.config.js
Modify build command to build with webpack/ts-loader instead of tsc
=> chore: use webpack for npm package build

.github/workflows/release.yml
=> chore: add node version to release workflow

packages/embed/CHANGELOG.md, packages/embed/src/utils/create-iframe/trigger-iframe-redraw.ts
=> fix(DIST-730): Fix redraw issue

src/core/views/components/iframe.js
=> fix(DIST-730): Remove display toggle that causes flicker

packages/embed/src/initializers/build-options-from-attributes.spec.ts, packages/embed/src/initializers/build-options-from-attributes.ts, packages/embed/src/utils/build-iframe-src.ts, packages/embed/src/utils/build-iframe.src.spec.ts
Merge #174 first.
When reviewing [filter out changes from PR #174](https://github.com/Typeform/embed/pull/175/commits/3bf33fb64d14853ad5a8267b5062d13617cbc774).
=> feat(DIST-703): Add support for disableTracking option

packages/demo-html/public/slider-html.html, packages/demo-html/public/slider-js.html, packages/embed/e2e/spec/functional/slider-window.spec.ts, packages/embed/e2e/spec/functional/slider.spec.ts, packages/embed/src/browser.ts, packages/embed/src/constants.ts, packages/embed/src/css/slider.scss, packages/embed/src/factories/create-popup/create-popup.spec.ts, packages/embed/src/factories/create-slider/create-slider.spec.ts, packages/embed/src/factories/create-slider/create-slider.ts, packages/embed/src/factories/create-slider/index.ts, packages/embed/src/factories/create-slider/slider-options.ts, packages/embed/src/index.ts, packages/embed/src/initializers/build-options-from-attributes.ts, packages/embed/src/initializers/index.ts, packages/embed/src/initializers/initialize-sliders.ts
=> feat(DIST-708): Add embed type slider

packages/demo-html/public/widget-html.html, packages/demo-html/public/widget-js.html, packages/embed/.prettierrc, packages/embed/e2e/spec/functional/widget.spec.ts, packages/embed/src/base/url-options.ts, packages/embed/src/initializers/build-options-from-attributes.spec.ts, packages/embed/src/initializers/build-options-from-attributes.ts, packages/embed/src/utils/build-iframe-src.ts, packages/embed/src/utils/get-transitive-search-params.spec.ts, packages/embed/src/utils/get-transitive-search-params.ts, packages/embed/src/utils/load-options-from-attributes.spec.ts, packages/embed/src/utils/load-options-from-attributes.ts
feat(DIST-700): Add transferableUrls parameters
Adds transferableURL parameters
=> feat(DIST-700): Add transitiveSearchParams

.github/workflows/pull-request-next.yml, .github/workflows/release.yml, .gitignore, packages/embed/.eslintignore, packages/embed/scripts/prepare-release.sh, packages/embed/src/initializers/initialize-popups.ts, packages/embed/src/initializers/initialize-sliders.ts, packages/embed/src/initializers/initialize-widgets.ts, packages/embed/src/utils/include-css.spec.ts, packages/embed/src/utils/include-css.ts, packages/embed/webpack.config.js
=> feat: Deploy to AWS S3

packages/demo-html/public/popup-html.html, packages/demo-html/public/popup-js.html, packages/demo-html/public/slider-html.html, packages/demo-nextjs/pages/popup.js, packages/embed/e2e/spec/functional/popup.spec.ts, packages/embed/src/constants.ts, packages/embed/src/css/popup.scss, packages/embed/src/css/slider.scss, packages/embed/src/factories/create-popup/create-popup.spec.ts, packages/embed/src/factories/create-popup/create-popup.ts, packages/embed/src/factories/create-slider/create-slider.spec.ts, packages/embed/src/factories/create-slider/create-slider.ts, packages/embed/src/initializers/initialize-popups.ts, packages/embed/src/initializers/initialize-sliders.ts
You can specify popup and slider size now.
=> feat: Add size, width and height to options

packages/demo-html/public/behavioral-html/exit-html.html, packages/demo-html/public/behavioral-html/load-html.html, packages/demo-html/public/behavioral-html/scroll-html.html, packages/demo-html/public/behavioral-html/time-html.html, packages/demo-html/public/behavioral-js/exit-js.html, packages/demo-html/public/behavioral-js/load-js.html, packages/demo-html/public/behavioral-js/scroll-js.html, packages/demo-html/public/behavioral-js/time-js.html, packages/demo-html/public/popup-html.html, packages/embed/e2e/cypress-utils.ts, packages/embed/e2e/spec/functional/behavioral-popup.spec.ts, packages/embed/src/factories/create-popup/create-popup.ts, packages/embed/src/factories/create-popup/popup-options.ts, packages/embed/src/initializers/build-options-from-attributes.spec.ts, packages/embed/src/initializers/build-options-from-attributes.ts, packages/embed/src/utils/create-custom-launch-options.spec.ts, packages/embed/src/utils/create-custom-launch-options.ts
Adds behavioural triggers to Embed
=> feat(DIST-705): Add behavioural triggers

README.md, packages/demo-html/README.md, packages/demo-nextjs/README.md, packages/demo-webpack/README.md, packages/embed/README.md
Is this documentation sufficient? Have we outgrown the README file and should generate a Github Pages docs with more examples?
=> docs: Update READMEs

demo/widget-tabs.html, package.json, src/core/features/google-analytics-instance-sharing.js, src/core/views/widget.js
We need to figure out how to release this as `0.*` version, not `1.*`.
=> fix(DIST-682): Send post message only if the form is present on page

src/core/views/components/iframe.js
[Ticket DIST-804](https://jira.typeform.tf/browse/DIST-804)
Fixes a small glitch in Safari not triggering redraw of the Form.
=> fix(DIST-804): Fix small render glitch in Safari browsers

packages/embed/src/base/actionable-options.ts
Adding `payload: { responseId: string }` in onSubmit type
=> Fix onSubmit type

packages/demo-html/public/behavioral-html/load-html.html, packages/demo-html/public/behavioral-html/scroll-html.html, packages/demo-html/public/behavioral-html/time-html.html, packages/demo-html/public/behavioral-js/load-js.html, packages/demo-html/public/behavioral-js/scroll-js.html, packages/demo-html/public/behavioral-js/time-js.html, packages/embed/src/factories/create-popover/create-popover.ts, packages/embed/src/factories/create-popup/create-popup.ts, packages/embed/src/factories/create-sidetab/create-sidetab.ts, packages/embed/src/factories/create-slider/create-slider.ts
Make sure all embed types (except widget) work with custom launch options / behavioral triggers.
Update demo to showcase launch options with each embed type.
=> fix(DIST-871): Custom launch options

packages/demo-html/public/callbacks.html, packages/demo-html/public/chat.html, packages/embed/README.md, packages/embed/src/utils/create-iframe/create-iframe.spec.ts, packages/embed/src/utils/create-iframe/get-form-event-handler.ts
Can be merged on https://github.com/Typeform/louvre/pull/1712 is released.
This will address #199
=> feat(DIST-891): Update event handler and add CUI docs and examples

packages/demo-html/public/chat.html, packages/demo-html/public/popover-html.html, packages/embed/e2e/spec/functional/chat.spec.ts, packages/embed/e2e/spec/visual/chat.spec.ts, packages/embed/src/css/popover.scss, packages/embed/src/factories/create-popover/create-popover.spec.ts, packages/embed/src/factories/create-popover/create-popover.ts, packages/embed/src/factories/create-popover/popover-options.ts, packages/embed/src/initializers/build-options-from-attributes.ts
[Ticket DIST-923](https://jira.typeform.tf/browse/DIST-923)
Adds a Notification Dot next to the chat UI button
=> feat(DIST-923): Add notification dot to chat

packages/embed/src/factories/create-popup/create-popup.spec.ts, packages/embed/src/factories/create-popup/create-popup.ts, packages/embed/src/factories/create-slider/create-slider.spec.ts, packages/embed/src/factories/create-slider/create-slider.ts
[Jira Ticket - WEB-1974](https://jira.typeform.tf/browse/WEB-1974)
Disabling the scrollbar preventing users to scroll when the popup or slider is open.
After closing it the scroll is back to its initial state.
=> feat(WEB-1974): Disabling scroll for popup and slider

packages/demo-nextjs/yarn.lock, packages/embed/README.md, yarn.lock
Supersedes #269 #265 #264 #263 #250
=> [DIST-1057] Update dependencies

packages/demo-nextjs/pages/_app.js, packages/demo-nextjs/pages/index.js, packages/demo-nextjs/pages/popover.js, packages/demo-nextjs/pages/popup.js, packages/demo-nextjs/pages/sidetab.js, packages/demo-nextjs/pages/slider.js, packages/demo-nextjs/pages/vanilla.js
Use a param to allow testing different forms
Keep default value as fallback
=> feat(DIST-123): Add id as param for embed demo

packages/embed/src/css/popover.scss, packages/embed/src/factories/create-popover/create-popover.ts
Ticket [DIST-1112](https://jira.typeform.tf/browse/DIST-1112)
- Icon should appear the same as the chat avatar, as a circular image
CUI in the share page is using the v1, so we need to update this version too.
=> fix(DIST-1112): Update custom icon to fit button size

packages/embed-react/package.json
=> [DIST-1124] Fix types location in package.json

packages/embed/src/css/popover.scss, packages/embed/src/factories/create-popover/create-popover.ts
An improvement to distorting not squared custom icons
=> fix(DIST-1138): Custom icon aspect ratio

.gitleaks.toml, packages/demo-html/public/widget-html.html, packages/embed/README.md, packages/embed/e2e/spec/functional/reload.spec.ts
This is clean up after PR #302 (DIST-1117). It adds docs and tests for the (re)load feature after customer confirmed the solution works for them.
=> chore(DIST-1130): Update readme and add tests

packages/demo-html/public/chat.html, packages/embed/src/css/popover.scss
Ticket [DIST-1112](https://jira.typeform.tf/browse/DIST-1112)
- The icon still did not look good on mobile
=> fix(DIST-1112): Fix custom icon on mobile

packages/demo-react/src/App.js, packages/embed-react/src/components/make-button-component.tsx
Hi,
I'm adding this feature to the API to allow customization of PopupButton wrapper HTML. Especially useful when, as a consumer, you already have your own elements structure, and design.
=> feat(DIST-1234): Customizable html for PopupButton

packages/embed-react/src/components/make-button-component.spec.tsx, packages/embed-react/src/components/make-button-component.tsx
=> fix(DIST-1269): Pass props to button component

packages/embed/README.md
=> chore(DIST-1237): Update README docs

.huskyrc, packages/demo-html/public/widget-html.html, packages/embed/README.md, packages/embed/src/base/url-options.ts, packages/embed/src/initializers/build-options-from-attributes.spec.ts, packages/embed/src/initializers/build-options-from-attributes.ts, packages/embed/src/utils/create-iframe/create-iframe.ts, packages/embed/src/utils/load-options-from-attributes.spec.ts, packages/embed/src/utils/load-options-from-attributes.ts, packages/embed/src/utils/setup-google-analytics-instance.spec.ts, packages/embed/src/utils/setup-google-analytics-instance.ts
Also allow passing GA tracking ID to specify which tracker to use.
=> fix(TYP-5406): Fix shareGaInstance feature

packages/embed-react/src/components/inline-style.spec.tsx, packages/embed/e2e/spec/functional/behavioral-popup.spec.ts, packages/embed/e2e/spec/functional/callbacks.spec.ts, packages/embed/e2e/spec/functional/chat.spec.ts, packages/embed/e2e/spec/functional/client-side.spec.ts, packages/embed/e2e/spec/functional/popover.spec.ts, packages/embed/e2e/spec/functional/popup.spec.ts, packages/embed/e2e/spec/functional/sidetab.spec.ts, packages/embed/e2e/spec/functional/slider.spec.ts, packages/embed/e2e/spec/functional/widget.spec.ts, packages/embed/e2e/spec/visual/mobile.spec.ts, packages/embed/src/css/popover.scss, packages/embed/src/css/popup.scss, packages/embed/src/css/sidetab.scss, packages/embed/src/css/slider.scss, packages/embed/src/css/widget.scss, packages/embed/src/factories/create-popover/create-popover.spec.ts, packages/embed/src/factories/create-popover/create-popover.ts, packages/embed/src/factories/create-popover/notification-days.ts, packages/embed/src/factories/create-popup/create-popup.spec.ts, packages/embed/src/factories/create-popup/create-popup.ts, packages/embed/src/factories/create-sidetab/create-sidetab.spec.ts, packages/embed/src/factories/create-sidetab/create-sidetab.ts, packages/embed/src/factories/create-slider/create-slider.spec.ts, packages/embed/src/factories/create-slider/create-slider.ts, packages/embed/src/factories/create-widget/create-widget.ts, packages/embed/src/factories/create-widget/elements/build-widget.spec.ts, packages/embed/src/factories/create-widget/elements/build-widget.ts, packages/embed/src/utils/create-iframe/get-form-event-handler.ts
This prevents conflicts with old embed SDK lib (when both libs are in one page).
=> feat(TYP-6029): Change CSS classnames prefixes

packages/demo-html/package.json, packages/demo-webpack/package.json, packages/embed-react/package.json, packages/embed/package.json
This project seems to be distributed with an MIT license now. However, tools like `license-checker` report that it is LGPL licensed because of the metadata does not match.
=> Update license metadata

packages/embed/src/utils/create-http-warning-banner.ts
Fixes embeds in wrapped PWAs #311. In Capacitor the URL is not parsed correctly via `new URL()`.
=> fix(DIST-1150): Update HTTP warning logic

.github/workflows/trigger-external-update.yml, docs/callbacks.md, docs/configuration.md, docs/contributing.md, docs/custom-embed.md, docs/hidden-fields.md, docs/index.md, docs/inline.md, docs/modal.md, docs/native-mobile-apps.md, docs/react.md, docs/vanilla.md
Documentation from https://developer.typeform.com/embed/ will be maintained here.
=> chore(DIST-1119): Add docs from developer portal

packages/embed/src/css/includes/_close.scss, packages/embed/src/css/popover.scss, packages/embed/src/css/popup.scss, packages/embed/src/css/sidetab.scss, packages/embed/src/css/slider.scss, packages/embed/src/css/widget.scss
Ticket DIST-1494 
- Fixes the close icon not being visible
=> fix(DIST-1494): Fix close icon color

packages/embed/src/css/includes/_fullsize.scss
related: https://github.com/postcss/autoprefixer/issues/1035#issuecomment-387247093
=> fix(DIST-1554): Autoprefix warning

.github/workflows/pull-request-next.yml, packages/embed/e2e/applitools-utils.ts, packages/embed/src/css/sidetab.scss, packages/embed/src/factories/create-sidetab/create-sidetab.ts
=> fix(DIST-1643): Change default sidetab icon size

packages/embed/src/base/url-options.ts, packages/embed/src/initializers/build-options-from-attributes.ts, packages/embed/src/utils/build-iframe-src.ts, packages/embed/src/utils/build-iframe.src.spec.ts, packages/embed/src/utils/hubspot.ts
Ticket DIST-1767
- Enables hubspot tracking in embed
=> feat(DIST-1767): Add hubspot tracking

docs/README.md
=> chore(DIST-1643): Add link to developer portal

.github/workflows/pull-request-next.yml, .github/workflows/release.yml
This commit needs to be "fix" in order to test the release job with update env vars.
=> fix(DIST-2000): Update github actions

.github/workflows/release.yml
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
=> chore(DIST-1695): Remove init job from release Github action

.github/workflows/pull-request-next.yml, package.json, packages/embed/package.json
Wait for approval on https://github.com/Typeform/typortal-chrome-extension/pull/33
=> chore(DIST-1898): Deploy PRs to AWS with hash

packages/demo-html/README.md
=> Fixed the popup.css link in HTML documentation.

packages/embed/src/base/sizeable-options.ts, packages/embed/src/css/widget.scss, packages/embed/src/factories/create-widget/elements/build-widget.spec.ts, packages/embed/src/factories/create-widget/elements/build-widget.ts
What
We're moving the widget size style to widget options to be compatible with other widgets.
=> fix(REACH-913): Apply min height to the widget iframe

packages/embed/package.json, packages/embed/webpack.config.js
Set correct CSS URL when serving the library via `yarn preview`.
=> chore(TU-520): Update CSS URL for `yarn preview`

packages/embed/src/factories/create-popup/create-popup.ts, packages/embed/src/factories/create-slider/create-slider.ts, packages/embed/src/factories/create-widget/create-widget.ts
=> feat(NOJIRA-123): Add aria-label to modal close button
