Typeform/embed

.travis.yml
package.json

Docs for semantic release say it should be configurable via `release` prop in package.json but it does not work. Passing the argument to the command directly seems to work.

chore(DIST-144): Update Travis npm release config

---

src/core/views/components/iframe.js

This should fix the error in functional tests in Travis. I was unable to replicate this locally. It passed in PR but failed on merge which is weird.
```
1) Popup Embed Widget Mobile Closes the Drawer widget clicking on close Button:
Uncaught TypeError: Cannot read property 'style' of null
This error originated from your application code, not from Cypress.
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.
https://on.cypress.io/uncaught-exception-from-application
at eval (webpack-internal:///./src/core/views/components/iframe.js:69:26)
```
The second commit here is explicit merge of `release` branch. When I …

fix(DIST-137): Iframe reference

---

.releaserc
package.json
yarn.lock

We have this [big epic](https://jira.typeform.tf/browse/FEAR-25). Basically the idea is to migrate all `npm` packages from `npm` registry to `GitHub` registry, so that nobody needs to go and create own personal `npm` tokens which we cannot dispose even if a person already left Typeform, because we don't know which `npm` token belongs to whom. So we need to migrate all existing packages to GitHub registry + publish to both registries, until the migration is finished and we can just remove all tokens from npm. Then everyone should setup their local env and repos to fetch `@typeform/` packages from `GitHub` registry. However, with Open Source libraries it's different because we need them to be published to `npm`, but be accessible for us (those who use `GitHub` registry for `@typeform` …

fix: Publish to both registries

---

README.md
src/core/make-fullscreen.js
src/core/make-fullscreen.spec.js
src/core/utils/index.js
src/core/utils/index.spec.js
src/core/views/mobile-modal.js
src/core/views/mobile-modal.spec.js
src/core/views/popup.js
src/core/views/popup.spec.js
src/core/views/widget.js
src/core/views/widget.spec.js

[DIST-41](https://jira.typeform.tf/browse/DIST-41)
- adds `takeSubmitEventData` which can be used to extend the details taken from the event. Currently it's just `response_id` passed from stakhanov (PR here: https://github.com/Typeform/stakhanov/pull/3481)
- adds tests for `takeSubmitData`
- makes `onSubmit` handlers to pass event to `takeSubmitEventData` to pass it to provided callback
- adds tests that `event` is passed to the util function `takeSubmitEventData`

feat(DIST-41): Add event data to onSubmit callback

---

.travis.yml
scripts/comment-preview-link

Install [Jarvis](https://github.com/Typeform/jarvis) package in Travis deploy job and use it for deployment to AWS. Since [Jarvis](https://github.com/Typeform/jarvis) is a private package we do not add it to dependencies in `package.json` or the installation for people from outside of the company would fail. It is installed only in the Travis CI deploy job and changes are not committed.

chore(DIST-242): Use Jarvis to deploy

---

.travis.yml

Embed lib does not have any proprietary @typeform packages as dependency. It installs @typeform/jarvis in Travis CI for deployment but it is not saved.

fix(DIST-304): Read @Typeform packages from Github

---

.releaserc
.travis.yml
package.json

New flow:
- installs tokens
- sets default registry for @typeform packages to be github
- installs private packages
- publishes to GitHub
- `semantic-release/exec` picks it up and runs `npm publish` for npm registry

fix(DIST-304): Rerelease the package

---

demo/demo.js
demo/full.html
demo/index.html
demo/popup.html
demo/widget-legacy.html
e2e/spec/functional/popup.spec.js
e2e/spec/functional/widget.spec.js
package.json
src/core/utils/index.js
src/core/utils/index.spec.js
test/fixtures.js

Report: [TYP-2386](https://jira.typeform.tf/browse/TYP-2386)
Bug introduced in [DIST-241](https://jira.typeform.tf/browse/DIST-241) by changing passing of hidden fields from query param to fragment.

fix(TYP-2386): Pass hidden fields via fragment

---

src/core/make-fullscreen.js

Bug [DIST-269](https://jira.typeform.tf/browse/DIST-269) in Safari is solved by code inspired by #53 from @prilutskiy

fix(DIST-269): Fix autofocus of full-screen form in Safari

---

src/core/views/popup.js

When a white typeform is embedded in a white page the box shadow separates the form:

fix(DIST-351): Add box shadow to side panel popup

---

README.md
demo/popup-api.html
demo/popup.html
demo/widget-legacy.html
demo/widget.html
e2e/spec/functional/popup.spec.js
e2e/spec/functional/widget.spec.js
src/core/attributes.js
src/core/attributes.spec.js
src/core/make-popup.js
src/core/make-widget.js
src/core/utils/url-parameters-transfer.js
src/core/utils/url-parameters-transfer.spec.js

The motivation of this change is to make it easier for Typeform users to pass specific dynamic parameters from the URL of the website they embed a Typeform into, to their Typeform. 
- Example 1: you have a website with a Typeform embedded in it, you users see ad on Instagram to your website, the user is directed to your website with a ```utm_source=instagram``` parameter, you set this `transferableUrlParameter` in the Typeform embed API and create a hidden field in your Typeform configuration, your Typeform is connected to Google sheet integration and you can now see where your users who completed the Typeform came from.
- Example 2: You want to personalize the Typeform displayed on the website dynamically to display contextual information like the name of the person filling the form if …

PI-81 Add option to transfer parameters from url to embed as hidden field

---

demo/behavioral-api/load-api.html
demo/behavioral-code/load-code.html
e2e/spec/functional/behavioral-popup.spec.js
src/core/make-popup.js
src/core/make-popup.spec.js
src/embed.js
src/embed.spec.js

When opening popup via behavioral triggers (for popover and side panel popup types) display icon to correctly indicate current state - opened, loading, closed.

fix(DIST-366): Display correct icon when popup is opened automatically

---

demo/behavioral-code/scroll-code.html
src/core/utils/popup-auto-open.js
src/core/utils/popup-auto-open.spec.js

Scroll top offset calculation was failing for HTML pages without proper DOCTYPE definition.

fix(DIST-370): Change scroll top calculation

---

demo/behavioral-api/scroll-api.html
demo/behavioral-code/scroll-code.html
src/core/utils/popup-auto-open.js
src/core/utils/popup-auto-open.spec.js

There is an issue when host page has CSS.
```
html {
overflow-y: scroll;
overflow-x: hidden;
height: 100%;
}
```
In that case we consider the page to have the same height as viewport, which is kind of correct (the <html> is 100%) but not really correct since page content overflows from <html>. See [DIST-453](https://jira.typeform.tf/browse/DIST-453) for details.

fix(DIST-453): Fix page height calculation

---

src/core/make-fullscreen.js
src/core/utils/index.js
src/core/utils/mobile-detection.js
src/core/utils/mobile-detection.spec.js
src/core/views/components/iframe.js
test/fixtures.js
webpack.config.js

Some forms are not displayed on iOS (see [DIST-459](https://jira.typeform.tf/browse/DIST-459)) because the <iframe> has width=0. This is due to an iOS hack introduced in 2017 (see [SB-731](https://jira.typeform.tf/browse/SB-731)) which seems to be no longer relevant.
This issue does not affect all forms, so it might be a conflict with host page CSS.
TODO:

fix(DIST-459): Remove iOS resize hack that is no longer needed

---

demo/popup-api.html

Update popup-api.html example. There is a simpler way to create side tab and popover via API and it preserves built-in functionality for opening / closing the popup.

chore: Update popup api example

---

src/core/make-popup.js
src/core/make-popup.spec.js
src/core/make-widget.js
src/core/make-widget.spec.js
src/core/utils/index.js
src/core/utils/index.spec.js
src/core/views/widget.js
src/core/views/widget.spec.js

When there are multiple forms on page the callbacks are triggered from other forms too.

fix: Check embed ID in "onReady" and "onClose" callbacks

---

README.md
demo/widget-api.html
src/core/attributes.js
src/core/attributes.spec.js
src/core/make-popup.js
src/core/make-popup.spec.js
src/core/make-widget.js
src/core/make-widget.spec.js

Adds the following metadata options and forwards them to renderer requests:
- source field as typeform-source query parameter. 
- medium field as typeform-medium query parameter. If empty set to embed-sdk
- mediumVersion field as typeform-medium-version query parameter
Uses existing open option and adds it as typeform-embed-trigger-type URL parameter.

feat(DIST-401): Add tracking parameters

---

README.md

Setting opacity of 0 is a bit surprising, background images won't show up as a result. When debugging, I was thinking it was a CSS issue, or a https (testing from my local environment).

Update Opacity in README.md

---

.github/workflows/release.yml

Use admin account Github token with write permissions for semantic release to push commit with changelog and bumped version in pacakge.json.

chore(DIST-589): Update release Github Action workflow

---

demo/index.html
demo/widget-real.html
src/core/make-widget.js
src/core/make-widget.spec.js
src/core/views/widget.js
src/core/views/widget.spec.js

When widget is opened as popup on mobile the iframe needs to be reloaded to make sure we display welcome screen again after the popup is closed. Our current logic stopped working.
https://jira.typeform.tf/browse/DIST-629
Widget with issue: https://embed-typeform.glitch.me/
Fixed widget (preview): https://embed.typeform.com/f647bf19c5aaccc56feaa25c397c117cfb8c0714/widget-real.html
Note: The issue is apparent only on mobile when widget is opened in popup.

fix(DIST-629): Update iframe reload logic

---

.github/CODEOWNERS
packages/embed/.eslintignore
packages/embed/css/styles.css
packages/embed/package.json

Eslint already checks prettier syntax for JS and TS files, this will check for other files too.

feat: Add prettier

---

packages/embed-kitchen-sink/stories/Popup.stories.js
packages/embed-kitchen-sink/stories/Widget.stories.js
packages/embed-kitchen-sink/stories/Window.stories.js
packages/embed/.eslintrc.js
packages/embed/src/factories/create-popup/create-popup.ts
packages/embed/src/utils/build-iframe-src.ts
packages/embed/src/utils/build-iframe.src.spec.ts
packages/embed/src/utils/create-iframe/create-iframe.spec.ts
packages/embed/src/utils/create-iframe/create-iframe.ts

We dont need whole URL, since we recommend "form" subdomain to avoid possible issues
when subdomain is changed. Standard subdomain "form" will always work.

feat: Use form ID instead of whole URL

---

packages/embed/src/base/embed-types.ts
packages/embed/src/factories/create-widget/create-widget.ts
packages/embed/src/factories/create-widget/widget-options.ts
packages/embed/src/utils/create-iframe/create-iframe.spec.ts

Same functionality can be achieved by a widget in full screen container.
We can add shorthand once widget is fully implemented, if necessary.
Also, adding widgets to end of body does not really make sense. It breaks single page apps (body is never reloaded) and on script reload it adds multiple forms.

feat(DIST-707): Remove full page type

---

.releaserc

Semantic Release throws an error due to the lack of a main branch in release config, this adds master as main branch and keeps next as a prerelease tag

chore(DIST-690): Add master as branch in release config

---

packages/embed/src/initializers/build-options-from-attributes.ts
packages/embed/src/utils/build-iframe-src.ts
packages/embed/src/utils/index.ts
packages/embed/src/utils/is-defined.spec.ts
packages/embed/src/utils/is-defined.ts
packages/embed/src/utils/remove-undefined-keys.ts

This is a [custom type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards), I recommend to read linked docs if you are not familiar with the concept.
We should use this check in place of `value != null` or `!!value` as those approaches might lead to unexpected behavior (eg. the latter will return false for `0` which is in most cases valid value).

feat: Add helper method isDefined

---

.github/workflows/pull-request-next.yml
.github/workflows/release.yml
package.json
packages/embed-react/package.json
packages/embed/README.md
packages/embed/package.json

While it is nice to develop a project on latest node, when we develop a library we should consider not all consumers will be using latest node. 
Lets try to support Node >=10+ as per https://nodejs.org/en/about/releases/
```
- 10 # end of life 2021-04-30
- 12 # end of life 2022-04-30
- 14 # end of life 2023-04-30
- 15 # current
```
We should test for each node version and remove them as their end of life date passes.
For example [CodeSandbox still uses Node 10 as default](https://codesandbox.io/docs/faq#can-i-change-the-node-version-used-in-a-container-sandbox).

chore: Switch to node 10, test for 10, 12, 14 and 15

---

packages/demo-html/public/popup-html.html
packages/demo-html/public/popup-js.html
packages/demo-html/public/slider-js.html
packages/demo-html/public/widget-html.html
packages/demo-html/public/widget-js.html
packages/demo-nextjs/pages/index.js
packages/demo-nextjs/pages/popup.js
packages/embed/e2e/spec/functional/popup.spec.ts
packages/embed/e2e/spec/functional/widget.spec.ts
packages/embed/src/base/base-options.ts
packages/embed/src/base/index.ts
packages/embed/src/constants.ts
packages/embed/src/css/popover.scss
packages/embed/src/css/popup.scss
packages/embed/src/css/sidetab.scss
packages/embed/src/css/slider.scss
packages/embed/src/factories/create-popover/popover-options.ts
packages/embed/src/factories/create-popup/popup-options.ts
packages/embed/src/factories/create-sidetab/create-sidetab.ts
packages/embed/src/factories/create-sidetab/sidetab-options.ts
packages/embed/src/factories/create-slider/slider-options.ts
packages/embed/src/factories/create-widget/widget-options.ts
packages/embed/src/initializers/build-options-from-attributes.spec.ts
packages/embed/src/initializers/build-options-from-attributes.ts
packages/embed/src/utils/build-iframe-src.ts
packages/embed/src/utils/build-iframe.src.spec.ts
packages/embed/src/utils/load-options-from-attributes.spec.ts
packages/embed/src/utils/load-options-from-attributes.ts

While writing docs I noticed we dont support hidden fields since we dont pass form URL but rather just its ID. 
Benefits of this approach is we take care of encoding hidden fields values and therefore users dont need to encode it themselves, eg. this is totally valid: `data-tf-hidden="name=John X. Doe,hobbies=music&sport,age=???"`.

feat: Add support for hidden fields

---

src/core/views/popup.js

We have to use flexbox instead of `translate(-50%, -50%)` to avoid blur.

fix(DIST-858): Popup position

---

.github/workflows/release.yml

This PR is to eliminate the following warning from the CI log:
```
jarvis Not invalidating Cloudfront cache as either $AWS_CLOUDFRONT_DIST or $PUBLIC_CDN_URL are not defined
```
Seems like this can cause jarvis to skip the cache invalidation step.

chore(DIST-893): Added missing cloudfront id (master)

---

.github/workflows/release.yml

This PR is to eliminate the following warning from the CI log:
```
jarvis Not invalidating Cloudfront cache as either $AWS_CLOUDFRONT_DIST or $PUBLIC_CDN_URL are not defined
```
Seems like this can cause jarvis to skip the cache invalidation step.

chore(DIST-893): Added missing cloudfront id (main)

---

src/core/utils/index.js
src/core/utils/url-parameters-transfer.js
src/core/utils/url-parameters-transfer.spec.js
test/fixtures.js

Resolves #274
**Context:**
```js
window.location = 'http://localhost/?empty-param=&filled=value' 
const urlParameters = ['empty-param', 'filled', 'non-existent']
```
**Before:**
```js
console.log(transferUrlParametersToQueryStrings(urlParameters, {}))
// { 'empty-param': '', 'filled': 'value', 'non-existent': undefined }
```
**After:**
```js
console.log(transferUrlParametersToQueryStrings(urlParameters, {}))
// { 'empty-param': '', 'filled': 'value' }
```
-------------------
**Before:**
```js
console.log(appendParamsToUrl('http://localhost/?foo=bar#some=thing', { 'undef': undefined }))
// http://localhost/?foo=bar&undef=undefined#some=thing
console.log(updateQueryStringParameter('undef', undefined, 'http://localhost/?foo=bar#some=thing'))
// …
```

fix(#274): Better way to handle empty querystring variables

---

src/core/views/widget.js
src/core/views/widget.spec.js

The transition between the welcome screen and the form
Causes the start-submission endpoint to be called twice
Thus registering two starts for each actual start
By adding `__dangerous-disable-submissions` it renders the welcome screen without calling the start submission endpoint
[DIST-1042](https://jira.typeform.tf/browse/DIST-1042)

fix(DIST-1042): Add disable submission to fake welcome screen on mobile

---

src/core/views/widget.js
src/core/views/widget.spec.js

Adding param 'typeform-welcome=0' to query string of the form URL will render it as inline widget even on mobile. Do not disable submissions or tracking in this case.

fix(DIST-1042): Allow embedding inline widget on mobile

---

packages/embed/e2e/spec/functional/close-on-keyboard.spec.ts
packages/embed/src/factories/create-popover/create-popover.ts
packages/embed/src/factories/create-popup/create-popup.ts
packages/embed/src/factories/create-sidetab/create-sidetab.ts
packages/embed/src/factories/create-slider/create-slider.ts
packages/embed/src/utils/create-iframe/create-iframe.ts
packages/embed/src/utils/create-iframe/index.ts
packages/embed/src/utils/create-iframe/setup-custom-keyboard-close.ts

Ticket [DIST-1005](https://jira.typeform.tf/browse/DIST-1005)
Closes Embed on Esc Key. 
ACs: 
1. form is embedded (all embeds except widget)
2. user opens the modal window
3. form is displayed
4. user presses ESC key
5. modal is closed
6. form is not displayed

feat(DIST-1005): Close embed on Keyboard event

---

packages/demo-html/public/reload-event.html
packages/embed/src/browser.ts
packages/embed/src/initializers/initialize-popovers.ts
packages/embed/src/initializers/initialize-popups.ts
packages/embed/src/initializers/initialize-sidetabs.ts
packages/embed/src/initializers/initialize-sliders.ts
packages/embed/src/initializers/initialize-widgets.ts
packages/embed/src/initializers/initialize.ts

When you inject embed snippet to the page later, you can load it manually via `window.tf.load()`.
You can reloading all existing embed snippets in the page via `window.tf.reload()`.

feat(DIST-1126): Allow reloading and loading snippets in page

---

packages/embed/README.md
packages/embed/src/utils/load-options-from-attributes.spec.ts
packages/embed/src/utils/load-options-from-attributes.ts

Array and object attributes can have values with coma. It needs to be escaped with backward slash.

fix(DIST-1131): Allow comas in hidden fields

---

packages/demo-html/public/behavioral-html/exit-html.html
packages/demo-html/public/client-side.html
packages/embed/e2e/spec/functional/client-side.spec.ts
packages/embed/src/browser.ts

Load also on lib load, not only on page load. In some cases the lib is injected into the page later,
after the page is already loaded and we want to load all embeds in the page at that time.

fix(DIST-1183): Load embed elements on lib load

---

packages/embed/src/css/includes/_fullsize.scss
packages/embed/src/css/popover.scss

Ticket [DIST-1161](https://jira.typeform.tf/browse/DIST-1161)
The height of the root container is set to `100%vh` when embedded in  in mobile, that height exceed the height of the device.
testable broken typeform on https://embedtestsite.000webhostapp.com/basic-typeform/
Sets the max height of the root to be not greater than the window.innerHeight, only for mobile devices

fix(DIST-1161): Fix height on mobile

---

src/core/views/widget.js
src/core/views/widget.spec.js

Remove disable submission from fake welcome screen on mobile. Some respondents are able to interact
with the placeholder form but we are unable to replicate this.
This will break insights (DIST-1042), but it will prevent losing submissions.
This reverts commit 8c50ecaad8786681e1247a55e8c0e1b91df1ca70 (PR #278).
Closes #318

fix(DIST-1199): Enable submission for fake welcome screen on mobile

---

packages/demo-html/public/callbacks.html
packages/demo-html/public/client-side.html
packages/embed/src/browser.ts

When lib is included in page before DOMContentLoaded event, wait for the event.
When it is included after page load, load snippets right away (based on document.readyState).
Resolves #363

fix(DIST-1195): Load embed snippets after the page has loaded

---

packages/embed/src/css/sidetab.scss

fix(DIST-1432): Prevent text from being hidden by ellipsis in side tab

---

packages/embed/src/base/modal-window-options.ts

By the way, shouldn't these JSDoc declarations include `undefined`?
Also, isn't it safer to end those lines with a semi-colon? I've never seen types declared like that, without semi-colons. Even tsc outputs them in *.d.ts* files.

fix(DIST-1237): ModalWindowOptions['autoClose'] can also be a boolean

---

packages/embed-react/src/components/inline-style.spec.tsx
packages/embed-react/src/utils/nonce.ts

As I mentioned [in this comment](https://github.com/Typeform/embed/issues/458#issuecomment-1043760286) I think I made a mistake in how I accessed the `__webpack_nonce__` global from within the component, because by the time we bundle it with Webpack, this global reference is lost/minified.
By referring to `global.__webpack_nonce__` rather than the bare `__webpack_nonce__`, we tell Webpack that this reference shouldn't change name during bundling.
Before this code, for the getNonce() function, after bundling we would emit:
```js
function getNonce() {
return  true ? __webpack_require__.nc : 0;
}
exports.default = getNonce;
```
And after this PR it looks like:
```js
function getNonce() {
return typeof __webpack_require__.g.__webpack_nonce__ !== 'undefined' ? …
```

fix(DIST-1525): read the nonce from a bundler-safe location

---

packages/embed/src/css/popover.scss
packages/embed/src/factories/create-popover/create-popover.ts

Before:
After:
Examples above are using custom icon from [Bootstrap Icons](https://icons.getbootstrap.com/icons/chat-quote-fill/).

fix(DIST-1550): Center custom icon in popover button

---

packages/embed/src/css/includes/_close.scss
packages/embed/src/css/includes/_mobile.scss

Before (desktop, mobile):
After (desktop, mobile):

fix(DIST-1549): Close button color on desktop

---

docs/react.md
packages/embed-react/src/components/make-button-component.tsx

Let me know if this is already possible with the react package and I am blind. 
But I have a use-case where there I need more than just the button click to open the popover. 
I didn't want to go too deep and create a popover with state that can be passed in (no-button), and instead wanted to keep a refactor recommendation minimal by just allowing a ref override on the existing component.
First PR here, so please let me know if there is anything else that I can provide!

feat(DIST-2005): @typeform/embed-react add the ability to pass custom ref to PopupButton

---

docs/react.md
packages/demo-nextjs/pages/_app.js
packages/demo-nextjs/pages/forward-ref.js
packages/embed-react/src/components/make-button-component.tsx

Fix for https://github.com/Typeform/embed/pull/546
@vandercloak were you able to pass `ref` to your button? I received a report it is not working and noticed we missed `React.forwardRef`.

fix(DIST-2005): Use React.forwardRef to pass ref

---

packages/embed/src/utils/setup-google-analytics-instance.spec.ts
packages/embed/src/utils/setup-google-analytics-instance.ts

- JIRA issue: [INT-4274](https://typeform.atlassian.net/browse/INT-4274)
On [INT-3774](https://typeform.atlassian.net/browse/INT-3774) we added the new gtag snippet to Louvre. 
⚠️ the old ga analytics.js will be discontinued on July
On this PT we added gtag support in order to send the client_id to louvre.
This is kind of unrelated to the migration itself, but if the users add a gtag script instead of ga, we can now support it.
To test it I used this html with an embed, that uses the gtag google script:
[embed-g4a-si.html.zip](https://github.com/Typeform/embed/files/10519526/embed-g4a-si.html.zip)
[INT-4274]: https://typeform.atlassian.net/browse/INT-4274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INT-3774]: …

feat(INT-4274): Send clientId for gtag

---

README.md

The previous link didn't work because the folder no-longer exists

chore(NOJIRA-1): Updated link to the react demo project

---

packages/embed/src/utils/setup-google-analytics-instance.ts

While fixing TYP-8260 noticed that sometimes we do not receive the trackingId directly.
With @mathio we discussed the possibility of reading it from dataLayer.
This PR addresses that issue, by iterating on dataLayer and fetching the trackingId in 'config'

fix(TYP-8260): Prevent undefined trackingId

---

docs/hidden-fields.md
package.json

Format docs with prettier. Add yarn command to run prettier also on docs.
*Note:* The source diff seems a bit weird, use rich diff to view changes.

fix(REACH-363): Update typo in docs on hidden fields

---

docs/index.md

WEB-6512
Update a link in the docs. We're no-more using the domain `developers.typeform.com`, for SEO reasons we wanna keep everything under `typeform.com`. The changed link was pointing to an outdated version of the developer portal and weirdly wasn't getting redirected to `typeform.com/developers`.
***Old version***
*** New version***

fix(WEB-6512): Update docs link

---

packages/embed/src/utils/setup-google-analytics-instance.ts

Inform developers their adblock might be preventing the Google Analytics from being loaded.
Resolves #588
The message is nicer now:

fix(REACH-578): Update error message for shareGaInstance

---

packages/demo-html/public/callbacks.html
packages/embed/src/base/actionable-options.ts

Match types defined in this lib with actual payload sent by the embedded form.
Resolves #577.

fix(REACH-573): Update types of payloads for callbacks

---

packages/embed/README.md
packages/embed/src/base/actionable-options.ts

For plans with "Redirect from ending screen" feature (currently plans Plus and above) the `onEndingButtonClick` callback also receives `ref` along with `formId`. The `ref` identifies the end screen where the button was clicked.
Resolves #584

feat(REACH-576): Add `ref` to the `onEndingButtonClick` payload type

---

packages/embed/src/css/includes/_close.scss

Update CSS to avoid possible conflicts with other general CSS styles of a <button>.
There was a conflict with some WP themes:
| before | after|
|--|--|
| ![Screenshot 2023-07-21 at 11 03 06](https://github.com/Typeform/embed/assets/1561771/a017f7b0-bfec-4ba0-9028-1bc72a862fc7) | ![Screenshot 2023-07-21 at 11 02 36](https://github.com/Typeform/embed/assets/1561771/24750fe8-8331-4f27-8bc6-34c449f44696) |

fix(REACH-644): Update close button CSS

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
.github/workflows/visual.yml
packages/embed/README.md
packages/embed/package.json

BREAKING CHANGE: The library no longer supports node version 14 (end of life 2023-04-30). While we officially do not support it anymore, there are no known issues at the moment and the library should work with this node version so far.

feat(REACH-800): Update CI to run on Node version 20

---

packages/demo-html/public/live-embed.html
packages/embed/e2e/spec/functional/live-embed.cy.ts
packages/embed/src/browser.ts
packages/embed/src/initializers/initialize-live-embeds.ts
packages/embed/src/initializers/initialize-popovers.ts
packages/embed/src/initializers/initialize-popups.ts
packages/embed/src/initializers/initialize-sidetabs.ts
packages/embed/src/initializers/initialize-sliders.ts
packages/embed/src/initializers/initialize-widgets.ts
packages/embed/src/initializers/initialize.ts
packages/embed/src/initializers/merge-options.spec.ts
packages/embed/src/initializers/merge-options.ts

Support hidden fields in embeds loaded with the `data-tf-live` attribute. Any property passed to that element (e.g. `data-tf-hidden` will overwrite the options saved in the live embed code.

feat(REACH-897): Support hidden fields in live embed codes

---

packages/embed/e2e/spec/functional/live-embed.cy.ts
packages/embed/src/utils/load-options-from-attributes.spec.ts
packages/embed/src/utils/load-options-from-attributes.ts

https://github.com/Typeform/embed/pull/621 introduced a bug in which, when loading a live embed code, boolean settings will always be set to `false` unless they are set to true in the element containing the `data-tf-live`.
This PR reverts that by enforcing that boolean settings should default to `undefined` if not found in the DOM element.

fix(REACH-914): wrong overlapping settings in live embed

---

.github/workflows/visual.yml
packages/embed/src/utils/set-element-size.spec.ts
packages/embed/src/utils/set-element-size.ts

When value with no units (string with numbers only) is provided, set size in pixels by default.
Both examples below will assume value in pixels:
```javascript
window.tf.createWidget(formId, {
height: "585",  // this PR fixes this case
});
window.tf.createWidget(formId, {
height: 585,
});
```

fix(NOJIRA-123): Set size in pixels by default

---

.github/workflows/trigger-external-update.yml

Trigger external updates to `developers` instead of the archived `dev-portal-content`

chore(TU-2561): Trigger external update to developers

---

packages/embed/package.json

Require Typescript version 4.4.0 in `@typeform/embed` by raising a deliberate TS error when using the package in lower versions.
This is necessary to use modern features such as Template Literals as object keys (see this issue: https://github.com/Typeform/embed/issues/631)
Resolves #631

fix(TU-7496): Require TS >=4.4.0

---

packages/embed/src/utils/build-iframe-src.spec.ts
packages/embed/src/utils/build-iframe-src.ts
packages/embed/src/utils/create-iframe/create-iframe.ts
packages/embed/src/utils/create-iframe/get-form-event-handler.spec.ts
packages/embed/src/utils/create-iframe/get-form-event-handler.ts
packages/embed/src/utils/create-iframe/handle-form-redirect.spec.ts
packages/embed/src/utils/create-iframe/handle-form-redirect.ts

For embedded forms if we let the embed SDK handle redirects it will avoid privacy issues in Safari (access to query params, opening new tabs).

feat(TU-8207): Handle form redirects in embed SDK

---

packages/embed/src/factories/create-popover/create-popover.spec.ts
packages/embed/src/factories/create-popover/create-popover.ts
packages/embed/src/factories/create-popup/create-popup.ts
packages/embed/src/factories/create-sidetab/create-sidetab.spec.ts
packages/embed/src/factories/create-sidetab/create-sidetab.ts
packages/embed/src/factories/create-slider/create-slider.ts

3rd parties might dispatch load event on iframe ([eg. Cookiebot](https://support.cookiebot.com/hc/en-us/community/posts/5512233219612-Cookiebot-blocks-native-DOM-events?page=1#community_comment_8880182477084)) before the iframe content is actually loaded, breaking the embed functionality (opening the modal window before it is opened by respondent).

fix(TU-15591): Listen to trusted iframe load events only

---

.github/workflows/pull-request.yml
package.json
packages/embed-react/package.json
packages/embed/package.json
sonar-project.properties

JIRA: https://typeform.atlassian.net/browse/TU-13733
Coverage reported [in SonarCloud](https://sonarcloud.io/summary/new_code?id=Typeform_embed&pullRequest=659), linked in [a comment below](https://github.com/Typeform/embed/pull/659#issuecomment-2288041027):

[TU-13733] Add SonarCloud configuration

---

packages/demo-html/public/live-embed.html
packages/embed/e2e/spec/functional/live-embed.cy.ts
packages/embed/src/initializers/initialize-live-embeds.ts

When the SDK is included multiple times, live embeds get loaded multiple times because they are loaded async. Customers may end up with multiple `embed.js` scripts in their website when they copy-paste multiple embed snippets into one page.
The issue is most visible when the embedded form opens automatically, eg. on load, [as reported in this community thread](https://community.typeform.com/share-your-typeform-6/form-popping-up-twice-14923).

fix(NOJIRA-123): Prevent loading live embed multiple times

---

docs/callbacks.md
packages/embed/README.md
packages/embed/src/base/actionable-options.ts

feat(TU-20040): Add `isClosed` to `onReady` callback payload

---

package.json
packages/demo-nextjs/app/layout.tsx
packages/demo-nextjs/package.json
packages/demo-nextjs/shared/menu.tsx
packages/demo-nextjs/tsconfig.json
yarn.lock

Required for https://github.com/Typeform/embed-demo/pull/64

chore(NOJIRA-123): Update React demo

---

packages/demo-nextjs/next-env.d.ts
packages/embed/src/factories/create-widget/create-widget.ts

Resolves #673
This behaviour is already existing for the Popup and Slider embeds so bringing this over to the Widget when the fullScreen option is enabled.

fix(TU-21474): Remove overflow on widget close

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

This PR updates the repository workflows to use temporary credentials generated by this action: https://github.com/aws-actions/configure-aws-credentials.
Before the workflow will run successfully, we will need to add the following Github Secret: `DEPLOYMENT_ROLE_ARN` with the value set to the appropriate role.

build(PLT-816): Update workflows to use temporary credentials

---

.github/workflows/pull-request.yml
packages/demo-html/public/live-embed-eu.html
packages/embed/e2e/spec/functional/live-embed-eu.cy.ts
packages/embed/src/constants.ts
packages/embed/src/initializers/initialize-live-embeds.ts
packages/embed/src/live-embed/fetch-live-embed.ts

This PR contains a forwards compatible change for the upcoming EU data region platform changes. We need to fetch the live  embed through a new API gateway and these changes reflect that.
* Add `data-tf-region` property to embed (note: we can't reuse `data-tf-domain` as this is a server side decorated property; we need something to infer the API gateway at runtime to allow future customers to configure this properly).

feat(PLT-1578): eu region option for live embed routing
